import React, {useState, useRef} from 'react';
import {
  Navbar,
  NavbarBrand,
  Nav,
  NavbarToggler,
  Collapse,
  NavItem,
  Button,
  Modal,
  ModalHeader,
  ModalBody,
  Form,
  FormGroup,
  Label,
  Input,
} from 'reactstrap';
import {NavLink} from 'react-router-dom';
import Generic from '../generic/Generic';
import {Animate, AnimateGroup} from 'react-simple-animate';
import useIntersection from '../generic/useIntersection';

const Home = () => {
  const ref = useRef() as React.MutableRefObject<HTMLInputElement>;
  const inViewport = useIntersection(ref, '0px'); // Trigger as soon as the element becomes visible
  const [showSpecials, updateShowSpecials] = useState(false);
  if (inViewport && showSpecials === false) {
    updateShowSpecials(true);
  }
  const specials = [
    {
      title: 'Spicy Lemon Chicken Kebab Recipe',
      ingredients: [
        '2 tablespoon Extra Virgin Olive Oil',
        '1 Red Bell pepper (Capsicum) - cut into squares',
        'Salt - to taste',
        '1 Onion - cut into chunks',
        '1 Chicken breasts - cut into cubes',
        '1 teaspoon Red Chilli flakes',
        '1 Lemon juice',
        '1 teaspoon Black pepper powder',
        '1 teaspoon Dried Thyme Leaves',
      ],
      totalTimeInMins: 90,
      cuisine: 'Indian',
      instructions: [
        'To begin making the Spicy Lemon Chicken Kebab Recipe, thoroughly wash and clean the chicken, and cut them into cubes.',
        'To marinate the chicken, in a mixing bowl, combine the chicken pieces along with the bell peppers and onions and lemon juice, dried thyme, red chilli flakes, pepper powder, olive oil, salt and mix well.',
        '  Rest it for at least for about 1 hour.',
        ' Once it is well coated and marinated, start skewering by first placing the red bell pepper, a chicken cube followed by a onion chunk, repeating the sequence one more time.',
        'Ensure the skewer is not over crowded and packed.',
        'Heat a grill pan, drizzle some oil and place the skewers and cook for at least 25 minutes.',
        'Keep brushing the extra marinade over the chicken and keep turning the skewers so that it is evenly cooked.',
        'Serve the Spicy Lemon Chicken Kebab Recipe, along with tzatziki dip, sliced onions and green chutney to make it more interesting.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/spicy-lemon-chicken-kebab-recipe',
      ingredientsUsed: [
        'salt',
        'red bell pepper (capsicum)',
        'red chilli flakes',
        'virgin olive oil',
        'onion',
        'lemon',
        'thyme leaves',
        'black pepper powder',
        'chicken breasts',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Spicy_Lemon_Chicken_Kebab_Recipe_.jpg',
      ingredientCount: 9,
      prepTimeInMins: 60,
      cookTimeInMins: 30,
      servings: 4,
      course: 'Appetizer',
      diet: 'Non Vegeterian',
    },
    {
      title:
        'Paneer Butter Masala Biryani Recipe - Layered Paneer Butter Masala Biryani Recipe',
      ingredients: [
        ' 1 sprig of mint',
        ' 1 tbsp cashews - for garnish',
        ' 1 bay leaf',
        ' 1/2 tsp garam masala powder',
        ' salt - as per taste',
        ' 1 sprig of green coriander',
        ' 1 tsp honey',
        ' 1/2 tsp cumin powder',
        ' 1/2 tsp red chilli powder',
        ' 200 grams of cottage cheese - cut into 1/2 inch cube',
        ' 1 onion - chop',
        ' 1 tsp ghee',
        ' 2 cups water',
        ' salt - oil',
        ' 2 tablespoons cream',
        ' 1 star anise',
        ' 3 cloves garlic',
        ' 1/4 cup onion - bottom Take',
        ' 2 whole black pepper',
        ' 1 tsp cardamom powder',
        ' 1/2 inch cinnamon',
        ' 1 cardamom',
        ' 1 tsp kasoori methi',
        ' 2 tomatoes',
        ' 2 long',
        ' 1 green chili ',
        ' 1 inch ginger',
        '1 cup rice',
        ' as per taste - As per use',
      ],
      totalTimeInMins: 45,
      cuisine: 'North Indian Recipes',
      instructions: [
        'To make Paneer Butter Masala Biryani recipe, first wash the rice and soak it for 30 minutes.',
        'To make rice for biryani, heat ghee in a pressure cooker.',
        'Add cardamom, long, star anise, cinnamon, whole black pepper, bay leaves, and cook for 1 minute.',
        'Now add rice, salt, 2 cups of water and close the cooker.',
        'Cook till 2 cities come and turn off the gas.',
        'Allow the pressure to drain automatically.',
        'Open the cooker and spread out the rice in a plate so that it becomes slightly cold.',
        'Now add fried onions, coriander leaves, mint and mix well.',
        'Keep it aside.',
        'To make Paneer Butter Masala for Biryani, heat oil in a pan.',
        'Add cumin, cardamom, green chillies, ginger, garlic, onion and cook till the onion turns brown.',
        'Now add tomatoes, salt and turn off the gas.',
        'Allow to cool.',
        'Now put this mixture in a mixer grinder and grind it into a paste.',
        'Heat some oil in a pan.',
        'Add the ground spices to it and cook for 1 minute.',
        'After this, add cumin powder, garam masala powder, red chili powder, honey, kasoori methi and let it cook on low flame.',
        'After the gravy boils, add cottage cheese, cream and mix it.',
        'Turn off the gas after 1 minute.',
        'To make biryani, grease a large bowl with butter.',
        'Add fried onions, mint leaves, coriander.',
        'Make a rice layer over it.',
        'Press it well.',
        'Now add Paneer Butter Masala to it.',
        'Re-insert these layers and place the rice on the topmost layer.',
        'Now place a plate over it and reverse it.',
        'Serve.',
        'Serve Paneer Butter Masala Biryani Recipe along with Bundi Raita and Papad for dinner.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/layered-paneer-butter-masala-biryani-recipe-in-hindi',
      ingredientsUsed: [
        'tomato',
        'cloves garlic',
        'kasoori methi',
        'onion',
        'cardamom',
        'salt',
        'green chilli',
        'cottage cheese cube',
        'cinnamon',
        'cashews',
        'garam masala powder',
        'star anise',
        'cardamom powder',
        'rice',
        'red chilli powder',
        'water',
        'mint',
        'coriander (dhania) leaves',
        'ginger',
        'ghee',
        'cumin powder',
        'bay leaf',
        'salt oil',
        'black pepper',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sneha-archanaskitchen.com/Layered_Paneer_Butter_Masala_Biryani_Recipe.jpg',
      ingredientCount: 24,
      prepTimeInMins: 20,
      cookTimeInMins: 25,
      servings: 4,
      course: 'Main Course',
      diet: 'Vegetarian',
    },
    {
      title: 'Udupi Style Ash Gourd Coconut Curry Recipe',
      ingredients: [
        '4 Dry Red Chillies',
        '1/2 teaspoon Turmeric powder (Haldi)',
        '1/2 teaspoon Mustard seeds',
        '1 Dry Red Chillies',
        'Sunflower Oil - for cooking',
        'Salt - to taste',
        '30 grams Tamarind Water',
        '1 cup Tamarind Water',
        '1/2 cup Fresh coconut - grated',
        '2 sprig Curry leaves - roughly torn',
        '500 grams Vellai Poosanikai (Ash gourd/White Pumpkin)',
        '1/2 teaspoon Methi Seeds (Fenugreek Seeds)',
        '2 teaspoons Sesame seeds (Til seeds)',
        '1 teaspoon Sunflower Oil',
        '3 tablespoons Jaggery',
        '2 teaspoons Coriander (Dhania) Seeds',
        '1/2 teaspoon Cumin seeds (Jeera)',
      ],
      totalTimeInMins: 40,
      cuisine: 'Udupi',
      instructions: [
        'To begin making the Udupi Style Ash Gourd Coconut Curry Recipe  cook the ash gourd in the pressure cooker with little water, turmeric powder and salt for just 1 whistle.',
        'Release the pressure naturally.',
        'Soak the tamarind ball in hot water for about 15 minutes, and squeeze and keep the water.',
        'Then dry roast the spices and other ingredients for the ground paste in a pan except the coconut.',
        'Then grind it along with coconut to a smooth paste.',
        'In same pressure cooker which has the ash gourd add the paste and little water and give it stir.',
        'Keep the Udupi Ash Gourd Coconut Curry on the medium heat, Adjust the seasoning and texture if required.',
        'Once done transfer it in a bowl.',
        'For the seasoning, heat oil in a small skillet and add mustard seeds and let it crackle.',
        'After the mustard seeds have crackled add the curry leaves and red chillies.',
        'Tun off the heat after the red chillies have darkened and add it on top of the Udupi Style Ash Gourd Coconut Curry and serve.',
        'Serve the Udupi Style Ash Gourd Coconut Curry Recipe along with steamed rice, Elai Vadam  and Pisarna Manga for lunch.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/udupi-style-ash-gourd-coconut-curry-recipe',
      ingredientsUsed: [
        'salt',
        'tamarind water',
        'coconut',
        'mustard seeds',
        'jaggery',
        'vellai poosanikai (ash gourdwhite pumpkin)',
        'curry leaves',
        'dry red chillies',
        'coriander (dhania) seeds',
        'methi seeds (fenugreek seeds)',
        'cumin seeds (jeera)',
        'turmeric powder',
        'sesame seeds (til seeds)',
        'sunflower oil',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Udupi_Style_Ash_Gourd_Coconut_Curry_Recipe_.jpg',
      ingredientCount: 14,
      prepTimeInMins: 10,
      cookTimeInMins: 30,
      servings: 4,
      course: 'Lunch',
      diet: 'Vegetarian',
    },
    {
      title: 'Mexican Style Black Bean Burrito Recipe',
      ingredients: [
        '6 to 8 Spinach Leaves (Palak)',
        '1/4 cup Black beans - soaked overnight and  cooked',
        '4 tablespoons Cheddar cheese',
        '1 Onion - chopped',
        '2 cloves Garlic - chopped',
        '1 cup Rice - or brown rice',
        '2 sprig Coriander (Dhania) Leaves',
        '1 Lemon juice',
        '4 tablespoon Hung Curd (Greek Yogurt)',
        '4 Spring Onion Greens - chopped',
        '1 Tomato - chopped',
        '4 Tortillas',
      ],
      totalTimeInMins: 40,
      cuisine: 'Mexican',
      instructions: [
        'To begin making the Black Bean Burrito recipe, pick the coriander leaves and set aside, then finely slice the stalks.',
        'Keep it aside.',
        'Heat 1 tablespoon of oil in a heavy bottomed pan over a medium heat, add the chopped garlic and coriander stalks and fry till they become brown.',
        'Add the cooked beans, mix it well and cook for a minute.',
        'Add the rice and cook for further 5 minutes.',
        'Remove from the heat and add coriander leaves that were kept aside.',
        'For Salsa, toss together tomatoes, onions, spring onions, lime juice, coriander leaves, mix well using a fork and season to taste.',
        'Heat the tortillas on a griddle pan till it softens.',
        'Lay it on a plate.',
        'Layer spinach leaves over the  tortilla.',
        'Spoon one-quarter of the fried rice and beans, top with a generous spoonful of salsa.',
        'Grate over some cheese and add a spoon of yoghurt.',
        'Wrap up the burrito, then tuck it in.',
        'Repeat with the remaining ingredients to make the rest of the burritos.',
        'Serve Black Bean Burrito with a side of chips and a healthy Green Apple, Radish & Pepper Salad  and a glass of Carrot Pineapple Orange Juice Recipe to make a delicious lunch or dinner.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/black-bean-burrito-recipe',
      ingredientsUsed: [
        'tomato',
        'spring onion greens',
        'hung curd (greek yogurt)',
        'black beans',
        'cloves garlic',
        'rice brown rice',
        'coriander (dhania) leaves',
        'onion',
        'lemon',
        'cheddar cheese',
        'spinach leaves (palak)',
        'tortillas',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Madhuri_Aggarwal/Black_Bean_Burrito.jpg',
      ingredientCount: 12,
      prepTimeInMins: 10,
      cookTimeInMins: 30,
      servings: 4,
      course: 'Lunch',
      diet: 'Vegetarian',
    },
    {
      title: 'Homemade Baked Beans Recipe (Wholesome & Healthy)',
      ingredients: [
        '250 grams Dry beans - (such as cannellini or soya beans)',
        '1 teaspoon Cumin powder (Jeera)',
        '1/4 teaspoon Red Chilli powder - or cayenne pepper',
        '1 Onion - finely chopped',
        '1 clove Garlic - grated',
        '1 teaspoon Extra Virgin Olive Oil',
        '1 tablespoon Honey - or more to taste',
        '500 grams Tomatoes - pureed',
        'Salt and Pepper - (coarsely pounded pepper) to taste',
        '1 teaspoon Dried oregano',
      ],
      totalTimeInMins: 120,
      cuisine: 'Fusion',
      instructions: [
        'To begin making the homemade baked beans recipe, we first have to soak the beans overnight for about 8 hours in water.',
        'We also have to make the cooked tomato puree.',
        'Click here to see the recipe of how to make tomato puree at home.',
        'Once the beans are soaked well, our next step is to cook them.',
        'I like using the pressure cooker method to cook the beans.',
        'Place the beans in the pressure, place the weight on, cover the pan and cook it along with 2-1/2 cups of water.',
        'After you heat 4 to 5 whistles, turn the heat to low and cook for another 15 minutes.',
        'Turn off the heat and allow the pressure cooker to release its pressure naturally.',
        'This would take another 10 minutes.',
        'The beans continue to cook under the pressure even when it is turned off.',
        'Once the pressure is released, open the cooker and drain out the excess liquids.',
        'You store this liquid and use it in the vegetable stock or risotto.',
        'Once the beans are cooked, our next step is to spice it up to make the baked beans.',
        'Heat oil in a sauce pan on medium heat; add in the onions and garlic and give it a light sauté until the onions are tender.',
        'Add the tomatoes, honey and the spices and give it a stir.',
        'Add in the cooked drained beans into the tomato gravy.',
        'Stir fry the beans until the beans get well coated with the tomatoes.',
        'Cover the pan, turn the heat to low and simmer the beans for about 30 minutes until you noticed the beans are well coated with the spices and tomatoes.',
        'Check the salt and seasoning levels and adjust to suit your taste.',
        'You can optionally garnish the Homemade Baked Beans with coriander leaves and serve it along with toast, or Potato Cakes Recipe.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/homemade-baked-beans-recipe-wholesome-healthy',
      ingredientsUsed: [
        'tomato',
        'salt',
        'cumin powder (jeera)',
        'pepper ( pepper)',
        'cloves garlic',
        'virgin olive oil',
        'onion',
        'dry beans (such cannellini soya beans)',
        'red chilli powder cayenne pepper',
        'dried oregano',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/World_Breakfast/Homemade_baked_beans_Recipe_healthy_breakfast_shutterstock_222439996.jpg',
      ingredientCount: 10,
      prepTimeInMins: 60,
      cookTimeInMins: 60,
      servings: 4,
      course: 'High Protein Vegetarian',
      diet: 'Vegetarian',
    },
    {
      title: 'Veg Chili Cheese Burgers Recipe',
      ingredients: [
        '1 tablespoon Tabasco Original - Hot Sauce',
        '5 Pickled Jalapenos - sliced',
        '1 Onion - chopped',
        '1 Whole Egg',
        '1 teaspoon Red Chilli flakes',
        '1 tablespoon Red Chilli powder',
        '1 Onions - chopped',
        'Salt - to taste',
        '2 Cheese Slices',
        '2 Burger buns',
        '2 Potatoes (Aloo) - pressure cooked',
        '4 cloves Garlic - chopped',
        '1 tablespoon Dried oregano',
        '1 cup Homemade tomato puree',
        '2 Tomatoes - chopped',
        '1/2 cup Soy granules',
        '1 Green Bell Pepper (Capsicum) - chopped',
        '1/2 cup Whole Wheat Bread crumbs',
        '1 teaspoon Honey',
        '1 tablespoon Cumin powder (Jeera)',
        'Sunflower Oil',
      ],
      totalTimeInMins: 55,
      cuisine: 'Continental',
      instructions: [
        'To begin making the Veg Chili Cheese Burgers Recipe, we will first pressure cook the potatoes and keep it ready.',
        'Cook them for 5 whistles in a pressure cooker.',
        'Once done allow the pressure to release naturally and peel off the skin.',
        'Add them into a bowl and mash it using a potato masher.',
        'Add onions, salt and red chilli powder and bind it together.',
        'Shape them into medium sized cutlets and leave it in the fridge to rest until you move on to make the sauce.',
        'To make the sauce, heat a flat skillet with oil on medium heat, add garlic and allow it soften for few seconds.',
        'Add chopped onions and saute until they turn golden brown.',
        'Add chopped capsicum and saute for a few minutes.',
        'Add in chopped tomatoes and sprinkle with a bit of salt and saute till they turn mushy.',
        'Also add in the tomato puree and all the seasonings like, red chilli powder, cumin powder, red chilli flakes, dried oregano, tobacco sauce and honey.',
        'Keep sautéing until the tomatoes are cooked, you will notice the tomatoes will change color and the raw smell goes away.',
        'At the end add the soya granules and salt to taste.',
        'Add about 1/4 cup of water and allow it to boil for 4-6 minutes minutes.',
        'Let the sauce be little gravish.',
        'Switch off the heat, heat a flat skillet for the patties to shallow fry them.',
        'Take the patties out of the fridge.',
        'Beat an egg into a bowl and also keep the bread crumbs ready over a plate.',
        'Carefully dip the patties into the egg and place them over the bread crumbs and coat them well on either side Dust off the excess bread crumbs.',
        'Place the crumb dipped patties on to the hot skillet and drizzle some oil on top.',
        'Cook on either side for atleast 10 minutes.',
        'Till you can see brown color crispy layer on top.',
        'Do the same for the rest of the patties and set aside.',
        'Once done, add a tablespoon of butter on the same skillet and cut the burger bun in to half horizontally and toast them on the tawa.',
        'Toast till the burger buns are golden brown and crisp.',
        'Take a cooked patty, spoon two tablespoon of the sauce on top, place a cheese slice over it and microwave the patty for just 10 seconds until you see the cheese melt.',
        'Take the patty out, spread some of the sauce on the base of the burger bun and place the patty with cheese on top and add few slices of jalapeno and close it with the burger top and serve.',
        'Do the same for the rest of the burger.',
        'Serve the Veg Chili Cheese Burgers Recipe along with baby potato stir fry and Mango Iced Tea Recipe to make it a complete meal.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/veg-chili-cheese-burgers-recipe',
      ingredientsUsed: [
        'cheese',
        'salt',
        'burger buns',
        'potato (aloo) pressure',
        'tomato',
        'soy granules',
        'eggs',
        'cumin powder (jeera)',
        'tabasco original sauce',
        'sunflower oil',
        'red chilli powder',
        'cloves garlic',
        'red chilli flakes',
        'jalapenos',
        'onion',
        'green bell pepper (capsicum)',
        'wheat bread crumbs',
        'dried oregano',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl-archanaskitchen.com/Veg_Chili_Cheese_Burgers_Recipe.jpg',
      ingredientCount: 18,
      prepTimeInMins: 10,
      cookTimeInMins: 45,
      servings: 4,
      course: 'Main Course',
      diet: 'Vegetarian',
    },

    {
      title: 'Singapore Style Chicken Layered Fried Rice Recipe',
      ingredients: [
        '2 Spring Onion Greens - finely chopped',
        '1 teaspoon Chinese 5 Spice Powder',
        '1 teaspoon White pepper powder',
        '1 tablespoon Sweet and Spicy Red Chilli Sauce (Tomato Chilli Sauce)',
        '1 tablespoon Vinegar',
        '1 Carrots (Gajjar) - cubed',
        '1/2 cup Classic Mayonnaise (With Egg)',
        '1 tablespoon Red Chilli sauce',
        '1 Green Bell Pepper (Capsicum) - sliced',
        '2 tablespoons Tomato Ketchup',
        '1/2 teaspoon Cumin powder (Jeera)',
        '2 tablespoons Red Chilli sauce',
        '2 cups Rice - soaked for 10 minutes',
        'Salt - to taste',
        '1 Spring Onion (Bulb & Greens) - chopped',
        '1 tablespoon Lemon juice',
        '3 teaspoons Sunflower Oil',
        '2 Green Chillies - slit and roasted',
        '1 teaspoon Garlic - minced',
        '1 tablespoons Soy sauce',
        '1/2 teaspoon Red Chilli powder',
        '1 tablespoons Garlic - crushed',
        '300 grams Boneless chicken - cut into 1/2 inch cubed',
        '1 tablespoons Ginger - crushed',
        '1 Onions - cubed',
        '2 Green Chillies - chopped',
        '250 grams Egg noodles - boiled and tossed in a teaspoon oil',
        '1 teaspoon Black pepper powder',
      ],
      totalTimeInMins: 75,
      cuisine: 'Asian',
      instructions: [
        'To begin making Singapore Style Chicken Layered Fried Rice Recipe, keep all the ingredients prepped and ready.',
        'Marinate the chicken cubes by combining chicken with spring onions, garlic, green chilies, soya sauce, lemon juice, black pepper, red chili powder, cumin, chilli sauce, sweet and spicy sauce, and salt to taste in a mixing bowl.',
        'Allow chicken to marinate for about 30 minutes.',
        'You can meanwhile boil the noodles as per instruction on packet and drain it and keep it aside.',
        'Toss the noodles with teaspoon of oil to prevent them from sticking together.',
        'To make Mayonnaise SaucePrepare the mayo sauce by mixing mayonnaise, tomato ketchup, red chilli garlic sauce and vinegar.',
        'Keep aside in a bottle or a closed container.',
        'You can make this ahead of time and keep ready before a few days as well.',
        'To make Fried Rice Recipe:Cook the rice in a pressure cooker for two whistle and let the pressure releases naturally.',
        'Once done open the pressure cooker and fluff up rice and keep aside.',
        'To make fried rice recipe,heat oil in a wok.',
        'Once the oil is hot add ginger & garlic, and slit green chillies.',
        'Saute till the raw smell disappears, on a low flame such that the ginger garlic does not char.',
        'Now add carrots, saute for a minute, add all the vegetables, and saute on medium heat.',
        'Once they are a bit tender, and then add salt, 5 spice powder, white pepper powder and mix well.',
        'Add rice to the wok and toss till the spiced veggies mix well and turn off heat.',
        'Keep aside.',
        'To make Chicken:In another wok, heat a tablespoon oil and add the marinated chicken and cook covered.',
        'Saute occasionally till tender and cooked well.',
        'You can sprinkle a bit of water if you want, but the moisture in it is enough for chicken to cook.',
        'Assembling Singapore Style Chicken Layered Fried Rice RecipePlace a cup of cooked rice on the serving plate.',
        'Top it up with boiled noodles.',
        'Pour the prepared mayonnaise sauce.',
        'Put sauteed marinated chicken as the topmost layer of the layered fried rice.',
        'Serve Singapore Style Chicken Layered Fried Rice Recipe as a one pot meal for lunch, along with a dessert like Coconut Tapioca Pudding Recipe with Spicy Strawberry Sauce or Cinnamon Rice Pudding With Cherry Compote Recipe.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/singapore-style-chicken-layered-fried-rice-recipe',
      ingredientsUsed: [
        'spring onion greens',
        'cumin powder (jeera)',
        'carrot',
        'onion',
        'black pepper powder',
        'green chillies',
        'sunflower oil',
        'eggs noodles tossed oil',
        'salt',
        'soy sauce',
        'white pepper powder',
        'rice',
        'chinese spice powder',
        'red chilli powder',
        'garlic',
        'lemon',
        'classic mayonnaise (with eggs)',
        'sweet spicy red chilli sauce (tomato chilli sauce)',
        'boneless chicken',
        'ginger',
        'spring onion (bulb greens)',
        'tomato ketchup',
        'vinegar',
        'green bell pepper (capsicum)',
        'red chilli sauce',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Sadafabbasi79-yahoo.com/singapore_style_Chicken_fried_rice_Recipe_With_noodles.JPG',
      ingredientCount: 25,
      prepTimeInMins: 30,
      cookTimeInMins: 45,
      servings: 12,
      course: 'Main Course',
      diet: 'Vegetarian',
    },
    {
      title: 'Tofu Pulao Recipe',
      ingredients: [
        ' 3 long',
        ' 1 lentil sugar',
        ' 1 teaspoon cumin seeds',
        ' 1 tablespoon ginger garlic paste',
        ' 1 teaspoon coriander powder',
        ' 1 bay leaf',
        ' 1 cup tofu - cut',
        ' 2 tomatoes - chopped Take',
        ' coriander - to garnish',
        ' 2 onions - chopped',
        ' 2 green chillies - chopped',
        ' 1/2 capsicum (green) - red or yellow',
        ' 1/2 teaspoon turmeric powder',
        '1 cup rice',
        ' 1/2 teaspoon garam masala powder',
        ' salt - according to taste',
        ' 1/2 teaspoon red chilli powder',
        ' 2 tablespoons ghee',
      ],
      totalTimeInMins: 65,
      cuisine: 'Indian',
      instructions: [
        'To make Tofu Casserole, first wash and soak the rice for 1/2 hour.',
        'Drain and keep aside.',
        'Heat the ghee in a saucepan.',
        'After it gets hot, add cumin seeds and let it splutter.',
        'Add onion, green chilli, ginger garlic paste and let it cook till the onion turns brown.',
        'After that add tomatoes and capsicum to it and mix.',
        'Add red chili powder, turmeric powder, coriander powder, garam masala powder and let it cook for 5 to 7 minutes.',
        'After 7 minutes add salt to it with tofu and let it cook until the tofu turns light brown.',
        'Add rice and 2 cups of water and mix.',
        'Cover the pan and cook until the rice is cooked.',
        'Turn off the gas after cooking.',
        'Open after 5 minutes and garnish with green coriander.',
        'Serve Tofu Casserole with Spinach Raita, Kachumbar Salad and Papad for day or dinner.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/tofu-pulao-recipe-in-hindi',
      ingredientsUsed: [
        'turmeric powder',
        'salt',
        'tomato take',
        'rice',
        'ghee',
        'capsicum (green) red yellow',
        'red chilli powder',
        'lentil sugar',
        'ginger garlic paste',
        'coriander',
        'bay leaf',
        'onion',
        'coriander powder',
        'tofu',
        'green chillies',
        'cumin seeds',
        'garam masala powder',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Richa_Gupta/Tofu_Masala_Rice_Indian_Style.jpg',
      ingredientCount: 17,
      prepTimeInMins: 20,
      cookTimeInMins: 45,
      servings: 4,
      course: 'Dinner',
      diet: 'Vegetarian',
    },
    {
      title: 'Murgh Malaiwala Recipe - Chicken In Rich Creamy Gravy',
      ingredients: [
        '1 Onion - sliced',
        '4 teaspoon Ghee',
        '1/4 teaspoon Black pepper powder',
        '1 tablespoon Badam (Almond) - paste',
        '2 Bay leaf (tej patta)',
        'Salt - to taste',
        '1/2 cup Fresh cream',
        '1 inch Cinnamon Stick (Dalchini)',
        '1 cup Milk',
        '2 teaspoon Kasuri Methi (Dried Fenugreek Leaves)',
        '1 teaspoon Garlic - paste',
        '1/2 teaspoon Lemon juice',
        '2 tablespoon Fresh cream',
        '2 teaspoon Ginger - paste',
        '500 gram Chicken - cut into pieces',
        '2 Cardamom Powder (Elaichi)',
      ],
      totalTimeInMins: 180,
      cuisine: 'North Indian Recipes',
      instructions: [
        'To begin making the Murgh Malaiwala recipe, firstly clean and wash the chicken pieces and dry it.',
        'Soak kasuri methi leaves in 1/4th cup of water in a small bowl.',
        'Take a big bowl and add chicken, salt, pepper and mix it well.',
        'Refrigerate it for about 2 hours or more.',
        'After 2 hours, add garlic, ginger, lemon juice, almond paste and 2 tablespoons cream into the chicken and keep it aside for 20 minutes.',
        'Heat a heavy bottomed pan with ghee.',
        'Add cardamom powder and onions in the pan and let it cook till the onions become soft and translucent.',
        'Next, add the marinated chicken pieces and let it cook for 10 minutes.',
        'After 10 minutes, add in the cream, milk with cinnamon stick and bay leaf.',
        'Boil stirring occasionally till the chicken pieces are fully cooked and semi thick gravy consistency is formed.',
        'Strain the methi leaves and sprinkle on the gravy and stir it well.',
        'Let it cook for about a minute or two.',
        'Switch off the gas, cover the pan and let it sit for 10 minutes before serving.',
        'Serve Murgh Malaiwala along with Burani Raita, Garlic Naan and Jeera Rice for a weekend meal with your family.',
        '',
      ],
      url: 'https://www.archanaskitchen.com/murgh-malaiwala-recipe-chicken-in-rich-creamy-gravy',
      ingredientsUsed: [
        'salt',
        'bay leaf (tej patta)',
        'ghee',
        'milk',
        'gram chicken',
        'onion',
        'lemon',
        'badam (almond) paste',
        'cardamom powder (elaichi)',
        'black pepper powder',
        'cinnamon stick (dalchini)',
        'ginger paste',
        'kasuri methi (dried fenugreek leaves)',
        'garlic paste',
      ],
      imageUrl:
        'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/ruby_pathak-yahoo.com/Murgh_Malaiwala.jpg',
      ingredientCount: 14,
      prepTimeInMins: 150,
      cookTimeInMins: 30,
      servings: 4,
      course: 'Lunch',
      diet: 'Non Vegeterian',
    },
  ];
  return (
    <>
      <div
        id="intro"
        style={{
          backgroundImage: 'url(../../assets/images/food-background-1.jpeg)',
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
        className="bg-image shadow-2-strong vh-100 vw-100">
        <div
          className="mask vh-100 vw-100"
          style={{backgroundColor: 'rgba(0, 0, 0, 0.8)'}}>
          <div className="container d-flex align-items-center justify-content-center text-center h-100">
            <div className="text-white">
              <h1 className="mb-3">Learn Healthy and Tasty Recipes</h1>
              <h5 className="mb-4">Easy & Professional Indian recipes</h5>
              <a
                className="btn btn-outline-light btn-lg m-2"
                href="https://www.youtube.com/watch?v=c9B4TPnak1A"
                role="button"
                rel="nofollow noreferrer"
                target="_blank">
                Explore
              </a>
              <a
                className="btn btn-outline-light btn-lg m-2"
                href="https://mdbootstrap.com/docs/standard/"
                target="_blank"
                role="button"
                rel="noreferrer">
                Today's specials
              </a>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <h1 className="text-center my-5">Todays Specials</h1>
        <div className="d-flex flex-row flex-wrap" ref={ref}>
          <AnimateGroup play={showSpecials}>
            {specials.map((special, index) => (
              <div className="col-12 px-2 col-sm-4 mb-5">
                <Animate
                  start={{opacity: 0, marginTop: 100}}
                  end={{opacity: 1, marginTop: 0}}
                  duration={0.5}
                  sequenceIndex={index}>
                  <Generic.DishCard data={special} />
                </Animate>
              </div>
            ))}
          </AnimateGroup>
        </div>
      </div>
    </>
  );
};

export default Home;
